version: '3.8'

networks:
  app-network:
    name: app-network
    driver: bridge

services:
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  nest_app:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - mysql_db
    environment:
      JWT_SECRET: ${JWT_SECRET}
      JWT_LIFE: ${JWT_LIFE}
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      SALT: ${SALT}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      ROOT_URL: ${ROOT_URL}
    networks:
      - app-network

volumes:
  mysql_data: